### PR TITLE
init: fetching data from wikipedia

### PR DESCRIPTION
**Pull request by damlakayikci**
not so clean now, I'll organize it once you review the code

### CODE REVIEW

**Comment by serhan-cakmak** [comment]
Please don't forget to mention the reviewer next time.

**Comment by serhan-cakmak** [comment]
Additionally, it would be easier for us to trace the process if you connect the issue to your pr. Like this issue refers to #211.

**Comment by kristinatrajkovski** [comment]
As discussed in private, instead of adding a separate file I believe you should try to prepare for our future wikidara API as much as possible by adding your code to views and handling calls. You can take #212 as an example.

**Comment by kristinatrajkovski** [comment]
Tested out, I can clearly see a few paragraphs of Python's wikipedia page. LGTM

**Pull request merged**
