### PR TITLE
Change the judge0 logic for improving usability

### PR DESCRIPTION
**Pull request by Mutti499**
It was really worrying not knowing if we would run out of api quota so close to the presentation. To fix this, I always have the idea of a system that pulls a random key. I know it may sound silly but this would logically increase our allowance from 50 to 50*key_pool_size. Definitely worth a look. I've attached the test cases.

### CODE REVIEW

**Comment by Mutti499** [comment]
@serhan-cakmak take a look while you are chilling in ur house mate! You should put the api keys under .env file like
JUDGE0_API_KEY_POOL=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by halil-karabacak** [comment]
MAN! Take a breath and rest a little ...

**Comment by Mutti499** [comment]
The show must go on mate!

**Comment by serhan-cakmak** [comment]
Good job mate! It seems like you did well in CMPE160 course with this spectacular object oriented perception of yours.

**Pull request merged**
