### PR TITLE
PR of mobile/signup to mobile/dev 

### PR DESCRIPTION
**Pull request by halil-karabacak**
Berkay, implemented the signup page for mobile. Here's the PR of this to mobile/dev. We expect your reviews

### CODE REVIEW

**Comment by kristinatrajkovski** [comment]
Should the ios folder be commited? I think it should be in the .gitignore file

**Comment by halil-karabacak** [comment]
> Should the ios folder be commited? I think it should be in the .gitignore file

ahh you're right. We'll be fixing it.

**Comment by Mutti499** [comment]
@halil-karabacak  how is it goin?

**Comment by halil-karabacak** [comment]
Seems the structure of the commit has some issues. We talked with berkay and agreed on continuing on mobile/dev. This branch will be deleted.

**Pull request closed without merging**
