### PR TITLE
Login Signup and Authentications Implemented

### PR DESCRIPTION
**Pull request by Mutti499**
Extremelyy dedicated team work!! We implemented the 
* Login Page
* Signup Page 
* Database Connection between login signup and server
* Authentications for the users
 
Just a little change is neeeded for logouts. I will look deeply into that!

### CODE REVIEW

**Comment by poyrazogluyigit** [comment]
I'm not assigned to this PR, but since there are no conflicts with the base branch, I think if would be okay if we merged this branch with main. @ErayEroglu What do you think?

**Comment by ErayEroglu** [comment]
I am testing it right now, I will merge it if everything is okay

**Comment by ErayEroglu** [comment]
It works greatly, elinize saglik. I am merging it with main.

**Comment by Mutti499** [comment]
Well done matess! It was a really quite work!

**Pull request merged**
