### PR TITLE
Wikidata API implemented

### PR DESCRIPTION
**Pull request by Mutti499**
Me and Kristina implemented Wikidata API with features:
- Search url:
 Takes a search string as input and returns a dictionary containing "item details", "title", "description" and "match number"
- Results url:
Takes itemID as parameter and returns WIKI details about that item ( "item details", "title", "description", "latitude", "longitude", "inceptionYear", "styleLabel", "image", "wikipedia article link"), top 5 nearest items (by Manhattan distance), and top 5 items from the same period (by inception year)

related issue: #120

### CODE REVIEW

**Comment by halil-karabacak** [comment]
Hi, a brief comment at first glance. We don't need any .pyc, i.e bytecode files, you can add these and any other build/compilation related files to .gitignore. I will look in detail to code structure and give my feedback to your well designed code.

**Comment by Mutti499** [comment]
Yes, this is a good idea because these __pycache__ files will not be of any use to us anymore! Thanks man, I'm waiting for other feedbacks.

**Comment by halil-karabacak** [comment]
I have completed the review and it seems everything on point. I have taken a few notes about the placement of a few function, we can discuss later and now everything seems fine.

**Review by halil-karabacak — APPROVED** [review]
Good job

**Review by halil-karabacak — CHANGES_REQUESTED** [review]
Hey, sorry. I just realized this version uses sqlite instead of mysql as we agreed on. This requires a few changes.

**Comment by kristinatrajkovski** [comment]
I am not 100℅ sure when I say this, but I'm pretty sure the file that you are seeing is autogenerated and there is not much we can do about it. It is not a part of our database. @Mutti499?

**Review by halil-karabacak — DISMISSED** [review]
Another point. Currently it seems we have different endpoints for each search result. Instead we can transfer the requested search by the user as a JSON object over http for a single endpoint like /search/ etc. This may make things easier.

**Comment by Mutti499** [comment]
About database in this PR, we implemented sqlite instead of mysql to start from basic that generates auto sqlite file. However in our other branch database_search_api we are changed the database to MYSQL. So the database will be changed in our second PR which will be ready by tomorrow or today evening.

**Comment by Mutti499** [comment]
And for the improvement of the enpoint. It is noted and will be done with the completed frontend search task. I'll keep it for now and a related topic will be opened.

**Pull request merged**
