### PR TITLE
Database Api Documentation

### PR DESCRIPTION
**Pull request by kristinatrajkovski**
We have decided to add the documentation for database endpoints as well. We are including each functions description, parameters, return values etc. Following the example from wikidata documentation, we added the similar generation commands to the views of database_search and are currently testing them at http://127.0.0.1:8000/wiki_search/swagger/.

### CODE REVIEW

**Comment by Mutti499** [comment]
Okey they are almost finished but we need a extreme review.
@ErayEroglu @ceylingebes @poyrazogluyigit 
I need your final comments. From each of you.

You need to open web in local and test all the functions are working. Than you should navigate to http://localhost:8000/wiki_search/swagger/  and test our API.

**Comment by ceylingebes** [comment]
Hi, I started to reviewing the documentation and amazed by your work, well done! I had a minor question, I don't exactly know it is the desired output but in /wiki_search/results/{QID}/ request, its response returns all the datatype fields of inceptionYear, latitude, longitude as a www.w3.org link. I am attaching one of them below as an example.  
"inceptionYear": {
          "datatype": "http://www.w3.org/2001/XMLSchema#integer",
          "type": "literal",
          "value": "1992"
        }
        
It didn't cause any problems in user side so maybe we can ignore that even though it is not desired behaviour?

**Comment by poyrazogluyigit** [comment]
> Hi, I started to reviewing the documentation and amazed by your work, well done! I had a minor question, I don't exactly know it is the desired output but in /wiki_search/results/{QID}/ request, its response returns all the datatype fields of inceptionYear, latitude, longitude as a [www.w3.org](http://www.w3.org) link. I am attaching one of them below as an example. "inceptionYear": { "datatype": "http://www.w3.org/2001/XMLSchema#integer", "type": "literal", "value": "1992" }
> 
> It didn't cause any problems in user side so maybe we can ignore that even though it is not desired behaviour?

Maybe it has to do something with how WikiData serializes their data? In the meanwhile, I see no problem with the work so it can be merged. Good work everyone!

**Review by poyrazogluyigit — APPROVED** [review]
Good job everyone. I have looked at the API documentation and haven't seen any problems.

**Comment by Mutti499** [comment]
https://github.com/bounswe/bounswe2024group9/pull/186/commits/da725f1d503db848e3997ae534b0d0c395ba7da8 showed it works! @ErayEroglu waiting for you

**Comment by ErayEroglu** [comment]
Good job guys, elinize sağlık

**Pull request merged**
