### PR TITLE
Create User Authentication system

### PR DESCRIPTION
**Pull request by serhan-cakmak**
This PR addresses issue #220 . In order to test if the authentication system works or not, I created a superuser, which I shared with the group members. Then I tried to reach run_code endpoint, yet the application redirected me to the login page. The other endpoints can be protected with this system. Therefore, a group discussion is needed to address the user hierarchy.  

Note: I also changed the base of the url. Additionally, group members should notice that .env file is changed, as discussed in the group chat.

### CODE REVIEW

**Comment by Mutti499** [comment]
this code can not be merged since Damla and I didnt finished our models and register login logics. We should talk at the school tomorrow. I am opening our issue now!

**Comment by serhan-cakmak** [comment]
Hi @Mutti499 , I just wanted to help you while I can. Therefore, I added also a signup page. As I stated in commit description, error handling hasn't been handled yet,  you and @damlakayikci can work on that while @mehmeteminipekdal works on the front-end side of the login, signup and optionally home pages. 

@kristinatrajkovski can you help mutti on the solution of the conflict between this pr and the main? I might solve the conflict yet I am not sure which functions are currently being used.

**Comment by kristinatrajkovski** [comment]
@serhan-cakmak the code in `views.py` does not seem to be clean as it contains afew @login lines which are commented out. As I am not familiar with this do you mind clearly implementing what you wanted to do there or erase the code causing conflicts. I would also suggest merging with main locally as you can easily fix the conflicts. For the wiki search and result make sure to keep the functions added in #222

**Comment by serhan-cakmak** [comment]
Thanks @kristinatrajkovski  for the feedback. I left the commented line on purpose so that you can choose whether the visitors can search some queries without logging in or not. Thus, I would appreciate if you can decide on that and resolve the conflicts since it is easier to solve conflicts on github web and merging it afterwards. Specifically, when I try this feature of github, I noticed that I can commit resolved conflicts just by merging my branch to the main one. Since I do not want to merge my own branch to the main, I would prefer either you or @Mutti499 to follow the steps I mentioned above.

**Comment by serhan-cakmak** [comment]
@kristinatrajkovski and @Mutti499 please check out if the current state of the branch works as expected.

**Comment by Mutti499** [comment]
With our adjustments it became a powerful one! LGTM!!!!!

**Pull request merged**
