### PR TITLE
Optimize Backend for Performance Improvements

### PR DESCRIPTION
**Pull request by Mutti499**
With this PR I tried to solve the slow loading feed page. The backend is now much faster because of optimized queries. Also now I am sending one request to the backend it may ease things up a bit. Please check that out and give feedback

### CODE REVIEW

**Comment by damlakayikci** [comment]
I checked it just now, I can say it has improved a bit but it still seems a bit slow from a user point of view. Do you think can we make it any better?

**Comment by kristinatrajkovski** [comment]
Hi, I am jumping in since I am the reviewer of the issue and wanted to check the progress and status.

I agree that the behavior is a bit faster than it used to be.

I have tried running it. When I search something in the navbar I see the questions change on the feed but no search results from wiki offered or with clickable results. I believe this is not the expected behavior and a true bug. Can you check?

**Comment by kristinatrajkovski** [comment]
Great job fixing the issue. I have tested it out and UI seems fine to me. 

I will let the reviewers make the final check, but please make sure to delete the blocks of dead/commented out code and add meaningful comments and tests :)

**Comment by halil-karabacak** [comment]
Seems fine. Looking at the code, I can't think a better solution except maybe prefetching whenever user starts to type his password, username could be already filled so but just an idea and may lead to a lot more work than it should have. Nice job muttiiii!

**Review by serhan-cakmak — APPROVED** [review]
Great job @Mutti499 . There is a remarkable increase in responsiveness.

**Pull request merged**
