### PR TITLE
Database Search API implemented #124

### PR DESCRIPTION
**Pull request by Mutti499**
#### Overview
This pull request introduces the `Database Search API` for the project, which encompasses functionality for handling routes, nodes, and users. It includes API endpoints to list entities, retrieve detailed information about specific entities, and create new entities. Additionally, a basic frontend interface is provided to interact with these endpoints.

#### by:

@Mutti499 
@kristinatrajkovski 

#### Details of Implementation

**API Endpoints:**
- **Routes:**
  - List all routes: `/routes/`
  - Retrieve a specific route by ID: `/routes/<int:pk>/`
- **Nodes:**
  - List all nodes: `/nodes/`
  - Retrieve a specific node by ID: `/nodes/<int:pk>/`
  - Create a new node: `/create_node/`
- **Users:**
  - List all users: `/users/`
  - Retrieve a specific user by ID: `/users/<int:pk>/`
  - Create a new user: `/create_user/`

**Frontend Features:**
- Basic forms for creating users and nodes.
- Navigation links to list and detailed view pages.

#### How to Test
- Use the forms on the main page to create new users or nodes and verify successful creation via list endpoints.

Side Notes:
> Super-user creation should not be accessible by web and mobile
> GET POST specifications did not implemented to the routes. I need more informations about that
> MYSQL server is at runing localy. It should be connected to a remote server

related issue: #126

### CODE REVIEW

**Comment by Mutti499** [comment]
@halil-karabacak can you review our code when you are avaliable

**Comment by halil-karabacak** [comment]
> @halil-karabacak can you review our code when you are avaliable

Sure!! I probably may not be able to do it today so let's set review deadline to 22/04/2024.

**Comment by Mutti499** [comment]
Okey mate no problem!

**Comment by Mutti499** [comment]
Did @kristinatrajkovski really do that!

avatars-X23RlijAWukQQ1JX-UvG9Uw-t240x240

**Comment by kristinatrajkovski** [comment]
Oh come oooon 😅 it was an accident

**Pull request merged**
